---

- hosts: localhost
  become: true
  tasks:
    - name: Update apt index
      apt:
        update_cache: yes

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - jq
          - wget
#          - awscli
          - postgresql
          - postgresql-contrib
          - git
#          - zsh # https://phoenixnap.com/kb/install-zsh-ubuntu
          - vim-nox # https://www.cyberciti.biz/faq/howto-install-vim-on-ubuntu-linux/
          - openconnect
          - build-essential
          - procps
          - file
          - libssl-dev
          - pkg-config
          - libsqlite3-dev
          - python3-pip
          - xclip
          - cloc
          - ripgrep # grep for in parent folder
        state: latest
        update_cache: true

    - name: Install kubectl
      community.general.snap:
        name: kubectl
        classic: yes
        channel: 1.27/stable

    - name: Install kubectx
      community.general.snap:
        name: kubectx
        classic: yes

    - name: Install helm
      community.general.snap:
        name: helm
        classic: yes

    - name: Install code
      community.general.snap:
        name: code
        classic: yes

    - name: Install k9s
      community.general.snap:
        name: k9s
        classic: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu lunar stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
        state: latest
        update_cache: true

    - name: create docker group
      command: addgroup --system docker
      
    - name: Adding users to group docker
      command: adduser $USER docker

    - name: Adding user to group docker again
      command: usermod -aG docker $USER

    - name: Create docker directory
      file:
        path: /home/callaghan/.docker/cli-plugins
        state: directory
      
    - name: Download docker-compose
      ansible.builtin.get_url:
        url: 'https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-linux-x86_64'
        dest: /home/callaghan/.docker/cli-plugins/docker-compose

    - name: chmod docker-compose
      file:
        dest: /home/callaghan/.docker/cli-plugins/docker-compose
        mode: +x
