---

- hosts: localhost
  become: true
  tasks:
    - name: Update apt index
      apt:
        update_cache: yes

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
#        update_cache: true
#    - name: Install kubectx
#      apt:
#        name: kubectx
#        state: latest

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - jq
          - wget
          - awscli
          - postgresql
          - postgresql-contrib
          - git
          - zsh # https://phoenixnap.com/kb/install-zsh-ubuntu
          - vim-nox # https://www.cyberciti.biz/faq/howto-install-vim-on-ubuntu-linux/
          - openconnect
          - flameshot
          - build-essential
          - procps
          - file
        state: latest
        update_cache: true

#    - name: set zsh as default shell
#      command: chsh -s $(which zsh)

#    - name: Install flameshot
#      community.general.snap:
#        name: flameshot
#        classic: yes

    - name: Install kubectl
      community.general.snap:
        name: kubectl
        classic: yes
        channel: 1.27/stable

    # next step is to run -> gcloud init
    - name: Install google-cloud-cli
      community.general.snap:
        name: google-cloud-cli
        classic: yes

    - name: Install postman
      community.general.snap:
        name: postman
        classic: yes

    - name: Install kubectx
      community.general.snap:
        name: kubectx
        classic: yes

#    - name: Install docker # errors do not use
#      community.general.snap:
#        name: docker
#        classic: yes

    - name: Install pycharm-professional
      community.general.snap:
        name: pycharm-professional
        classic: yes

    - name: Install go
      community.general.snap:
        name: go
        classic: yes

    - name: Install helm
      community.general.snap:
        name: helm
        classic: yes

    - name: Install code
      community.general.snap:
        name: code
        classic: yes

    - name: Install helix
      community.general.snap:
        name: helix
        classic: yes

    - name: Install k9s
      community.general.snap:
        name: k9s
        classic: yes

    - name: Install SMPlayer
      community.general.snap:
        name: smplayer
        classic: yes

    - name: Install sqlitebrowser
      community.general.snap:
        name: sqlitebrowser
        classic: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu lunar stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
        state: latest
        update_cache: true

    - name: create docker group
      command: addgroup --system docker
      
    - name: Adding users to group docker
      command: adduser $USER docker

    - name: Adding user to group docker again
      command: usermod -aG docker $USER

    - name: Create docker directory
      file:
        path: /home/callaghan/.docker/cli-plugins
        state: directory
      
    - name: Download docker-compose
      ansible.builtin.get_url:
        url: 'https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-linux-x86_64'
        dest: /home/callaghan/.docker/cli-plugins/docker-compose

    - name: chmod docker-compose
      file:
        dest: /home/callaghan/.docker/cli-plugins/docker-compose
        mode: +x


